### ISSUE TITLE
Initiate recording with this client?

### ISSUE THREAD

**Issue by voordev** [sipwise/janus-client#10]
Would it be possible to initiate a recording with this library using janus and the recording examples inside janus demo folder?

I look for a clean solution to implement this, node is not my native language but there are not much options out there. The provided javascript solution is not lean and overlay complex. 

Kind regards

**Comment by voordev** [comment]
Nobody?

**Comment by hpherzog** [comment]
Hi. If you mean the support of the janus_recordplay plug-in than it is currently not possible. This client currently supports the janus_videoroom plug-in only. It is currently not planned to implement it, but we are always open for contributions. 

Best Regards

**Comment by voordev** [comment]
Ok thank you I will investigate if its interesting to create a PR or look for another solution.
