### ISSUE TITLE
How to get sdp and media stream

### ISSUE THREAD

**Issue by messi49** [sipwise/janus-client#14]
How to get the offerSdp?

```
session.videoRoom().publishFeed(room, offerSdp).then((publisherHandle)=>{
    var answerSdp = publisherHandle.getAnswer();
    ...
});
```

Also, how to get and set the media stream?
Can we publish the uvc camera image?

**Comment by thuanjdev** [comment]
Help! I also encountered such a situation.

**Comment by hpherzog** [comment]
> How to get the offerSdp?
> 
> ```
> session.videoRoom().publishFeed(room, offerSdp).then((publisherHandle)=>{
>     var answerSdp = publisherHandle.getAnswer();
>     ...
> });
> ```

The offer sdp is created by the browser method [RTCPeerConnection.createOffer](https://developer.mozilla.org/de/docs/Web/API/RTCPeerConnection/createOffer). After creating the offer sdp, you send it via the signaling channel (WebSocket) to the server and delegate it to the method you quoted.

> Also, how to get and set the media stream?
> Can we publish the uvc camera image?

Media generation and modification is not part of this client. This client's purpose is restricted to the communication with the Janus WebRTC Server.
