### ISSUE TITLE
Unhandled error if websocket connection times out

### ISSUE THREAD

**Issue by juliusav** [sipwise/janus-client#17]
In the case of a Janus server not being available, the Janus client's ws connection attempt will timeout.

This leads to the Janus client removing all event listeners and trying to connect the ws again.

When the first ws connection attempt finally times out and throws an error, there is no longer a handler for it, resulting in the following:

> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ETIMEDOUT 54.227.144.109:443
>     at Object._errnoException (util.js:992:11)
>     at _exceptionWithHostPort (util.js:1014:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by robgonnella** [comment]
I took a crack at solving this one although it's difficult to test as race conditions usually are. I was able to produce an uncaught exception in a unit test and that test now passes. I also imported these changes into an existing janus client app I've been working on and everything seemed to work as expected there too.
https://github.com/sipwise/janus-client/pull/19

**Comment by juliusav** [comment]
Tested the latest version and validate that there is no more unhandled error :) thanks @robgonnella
