### ISSUE TITLE
Browser Compatibility?

### ISSUE THREAD

**Issue by RobertLowe** [sipwise/janus-client#5]
Consider switching to `websocket` https://www.npmjs.com/package/websocket `w3cwebsocket` standardization, this would enable `janus-videoroom-client` to be used in node & browser.

`ws` doesn't appear to play-nice with browsers https://github.com/websockets/ws/issues/938

Cheers

**Comment by hpherzog** [comment]
Sounds like a good idea. And it might be that we consider that. However, right now we are not focusing on a scenario were we want to control janus from the browser. But feel free to contribute here.

**Comment by EchoAbstract** [comment]
@hpherzog I've submitted an MR to fix this issue and have tested in the browser (a chrome extension that casts a tab) and in an electron app (running in the node process) that does complex sharing including screen (with simulcast) and audio.  I didn't have the ability to test a feed from the camera, but I don't imagine that should make much of a difference.

This has no client or API changes, but I'd think a major bump be good when releasing this, as it adds major new support.

BTW, this made making my extension super easy, so thanks for the library.

**Comment by hpherzog** [comment]
Thank you very much for your contribution. We appreciate that a lot. The change is under review.

Best Regards
Hans-Peter Herzog

**Comment by kirillt** [comment]
Curious, what is the stage of this PR? Browser compatibility would be really awesome since for server side it is possible to implement Janus plugin itself, but there is no means to write client code in modern JS as far as I could make my research.
