### ISSUE TITLE
Subscribe question

### ISSUE THREAD

**Issue by vsimon** [sipwise/janus-client#9]
Hi, I am trying to subscribe to a feed in a videoroom based on what I can piece together from the snippets in the README and I'm following what I think are the steps but no video stream is showing up. I was wondering if someone could check if these steps are correct:
 
Assuming I got the roomId (with a publisher feed in it) and client -> session -> videoRoomHandle set up ...
```
const feeds = await videoRoomHandle.getPlugin().getFeeds(roomId);

for (let feed of feeds) {
    const configuration = {iceServers: [{urls: 'stun:stun.l.google.com:19302'}]};
    const pc = new RTCPeerConnection(configuration);

    const listenerHandle = await session.videoRoom().listenFeed(roomId, feed);

    pc.onicecandidate = (event) => {
        if (event.candidate == null) {
            listenerHandle.trickleCompleted();
        } else {
            listenerHandle.trickle(event.candidate);
        }
    };

    pc.ontrack = function (event) {
        console.log('ontrack', event);
    };

    const listenerOffer = listenerHandle.getOffer();
    await pc.setRemoteDescription(listenerOffer);

    const listenerAnswer = await pc.createAnswer();

    await pc.setLocalDescription(listenerAnswer)

    await listenerHandle.setRemoteAnswer(listenerAnswer.sdp);
}
```

It seems `pc.ontrack` is being called immediately after the `pc.setRemoteDescription`. Is there anything missing I should be doing? Thanks.

P.S. I am also using this fix from: https://github.com/sipwise/janus-client/pull/8

**Comment by vsimon** [comment]
Closing. User error. :) This works, the video element I was using in 'ontrack' was being occluded by a local video element.

**Comment by saket424** [comment]
@vsimon,
Since I am a newbie, I would love to see your example index.js that shows both the publisher and subscriber video feeds that you got working. Can you make the code available as a gist or PR as a quick start reference for others wanting to use this sipwise code? Thanks in advance.
